# SPDX-FileCopyrightText: 2025 Javier Pérez
#
# SPDX-License-Identifier: CC0-1.0

name: Mirror GitLab repository

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  mirror-gitlab-repo:
    uses: coping chronicles/.github/.github/workflows/mirror.yml@main
    with:
      repository-url: https://gitlab.com/coping chronicles/coping chronicles.git
      rewrite-lfs: true
    secrets:
      token: ${{ secrets.MIRROR_TOKEN_GITHUB }}
