[package]
name = "coping-chronicles-client"
version = "0.17.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2021"

[lints]
workspace = true

[features]
simd = ["vek/platform_intrinsics"]
plugins = ["common-state/plugins"]
bin_bot = [
    "serde",
    "ron",
    "clap",
    "rustyline",
    "common-frontend",
    "async-channel",
    "voxygen-i18n-helpers",
    "client-i18n",
]
tracy = ["common-base/tracy"]
tick_network = []

default = ["simd"]

[dependencies]
common = { package = "coping-chronicles-common", path = "../common", features = [
    "no-assets",
] }
common-base = { package = "coping-chronicles-common-base", path = "../common/base" }
common-state = { package = "coping-chronicles-common-state", path = "../common/state", default-features = false }
common-systems = { package = "coping-chronicles-common-systems", path = "../common/systems", default-features = false }
common-net = { package = "coping-chronicles-common-net", path = "../common/net" }
network = { package = "coping-chronicles-network", path = "../network", features = [
    "compression",
    "quic",
], default-features = false }

byteorder = "1.3.2"
tokio = { workspace = true, features = ["rt-multi-thread"] }
quinn = { workspace = true, features = ["rustls"] }
rustls = { workspace = true }
hickory-resolver = { version = "0.24.0", features = [
    "system-config",
    "tokio-runtime",
] }
image = { workspace = true }
num = { workspace = true }
tracing = { workspace = true }
rayon = { workspace = true }
specs = { workspace = true, features = [
    "serde",
    "storage-event-control",
    "derive",
] }
vek = { workspace = true }
hashbrown = { workspace = true }
authc = { git = "https://gitlab.com/coping chronicles/auth.git", rev = "ae0e16783a9f9041951296885f082308e155db79" } # xMAC94x/current_master_till_refactored branch

#TODO: put bot in a different crate
#bot only
async-channel = { version = "2.1", optional = true }
voxygen-i18n-helpers = { package = "coping-chronicles-voxygen-i18n-helpers", path = "../voxygen/i18n-helpers", optional = true }
client-i18n = { package = "coping-chronicles-client-i18n", path = "i18n", optional = true }
common-i18n = { package = "coping-chronicles-common-i18n", path = "../common/i18n"}
serde = { workspace = true, features = ["rc"], optional = true }
ron = { workspace = true, optional = true }
clap = { workspace = true, optional = true }
rustyline = { version = "15.0.0", optional = true }
## logging
common-frontend = { package = "coping-chronicles-common-frontend", path = "../common/frontend", optional = true }

[dev-dependencies]
voxygen-i18n-helpers = { package = "coping-chronicles-voxygen-i18n-helpers", path = "../voxygen/i18n-helpers" }
client-i18n = { package = "coping-chronicles-client-i18n", path = "i18n" }

[[example]]
name = "chat_cli"
required-features = ["bin_bot"]

[[bin]]
name = "bot"
#authors = ["Avi Weinstock <aweinstock314@gmail.com>"]
required-features = ["bin_bot"]

[[bin]]
name = "swarm"
required-features = ["bin_bot", "tick_network"]
